<?php
/**
 * Title: Keuringen info
 * Slug: brekhoff/keuringen
 * Categories: categorie
 */
?>


<!-- wp:acf/content-keuringen {"name":"acf/content-keuringen","data":{"content-keuringen_eyebrow":"Waarom keuringen?","_content-keuringen_eyebrow":"field_content-keuringen_eyebrow","content-keuringen_title":"Keuringen zijn verplicht én essentieel","_content-keuringen_title":"field_content-keuringen_title","content-keuringen_content":"In Nederland zijn bedrijven wettelijk verplicht om periodieke keuringen uit te voeren. Dit is niet alleen om boetes te voorkomen, maar vooral om veiligheid te garanderen.","_content-keuringen_content":"field_content-keuringen_content","content-keuringen_items_0_icon":62,"_content-keuringen_items_0_icon":"field_content-keuringen_item_icon","content-keuringen_items_0_title":"Wettelijke verplichting","_content-keuringen_items_0_title":"field_content-keuringen_item_title","content-keuringen_items_0_text":"De Arbeidsomstandighedenwet verplicht werkgevers om regelmatig keuringen uit te voeren van elektrische installaties en brandveiligheidsvoorzieningen.","_content-keuringen_items_0_text":"field_content-keuringen_item_text","content-keuringen_items_1_icon":61,"_content-keuringen_items_1_icon":"field_content-keuringen_item_icon","content-keuringen_items_1_title":"Veiligheid medewerkers en bezoekers","_content-keuringen_items_1_title":"field_content-keuringen_item_title","content-keuringen_items_1_text":"Onveilige elektrische installaties of gebrekkige brandmeldinstallaties kunnen leiden tot gevaarlijke situaties. Keuringen identificeren risico's voordat ze problemen veroorzaken.","_content-keuringen_items_1_text":"field_content-keuringen_item_text","content-keuringen_items_2_icon":60,"_content-keuringen_items_2_icon":"field_content-keuringen_item_icon","content-keuringen_items_2_title":"Verzekeringseisen","_content-keuringen_items_2_title":"field_content-keuringen_item_title","content-keuringen_items_2_text":"Veel verzekeraars eisen actuele keuringscertificaten. Zonder geldige keuringen loop je het risico dat schade niet gedekt is.","_content-keuringen_items_2_text":"field_content-keuringen_item_text","content-keuringen_items":3,"_content-keuringen_items":"field_content-keuringen_items"},"mode":"preview"} /-->